### ISSUE TITLE
Loading acquisition dates blocks browser interaction

### ISSUE THREAD

**Issue by jisantuc** [stac-utils/stac-index#14]
Loading acquisition dates for items blocks browser interaction. This isn't the end of the world, but it is pretty annoying.

Replication:

- load https://stacindex.org/catalogs/world-bank-light-every-night#/2Y8qvpmgGXMkKYTC6V1qskx8HMfNqp5KvprH?t=items
- try to use the refresh button while acquisition dates are being populated
- note that your refresh isn't honored until after the acquisition date loads are all complete

**Comment by m-mohr** [comment]
Interesting! I get

> {"code":"ResourceNotFound","message":"/201206/201206_catalog.json does not exist"}
> 
> Please note that some servers don't allow external access via web browsers (e.g., when CORS headers are not present).
> 
> Errored URL: https://stacindex.org/api/201206/201206_catalog.json

for the URL due to CORS issues. I'm surprised that it works for you?!

Anyway, that is a STAC Browser issue and is not specific to STAC Index. I'll move this to stac-browser.

**Comment by jisantuc** [comment]
good point, that is really weird and doesn't make a ton of sense 🤔
