### ISSUE TITLE
1.0.0 (stable) compliance flag

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-index#15]
Add a flag that shows whether a tool or catalog is fully 1.0.0 (final) compliant.

**Comment by cholmes** [comment]
+1 - just had a similar thought. Mine was more about a 'reviewed' flag, like how we were thinking of a small group of people to review catalogs for being sensible (slowly turning that into tools that would warn on various best practices). 

The general use case of both to me is someone coming to STAC index for good examples to base their stuff on - it should be easy to find those.

**Comment by m-mohr** [comment]
For Catalogs, STAC Index encourages to make catalogs 1.0.0 compliant:

![grafik](https://user-images.githubusercontent.com/8262166/120104623-9ddfc180-c155-11eb-8043-d492bc120738.png)

**Comment by m-mohr** [comment]
Will not further invest for now as there is no simple solution right now without a lot of manual work.
