### ISSUE TITLE
Broken links to VITO openEO collections

### ISSUE THREAD

**Issue by jdries** [stac-utils/stac-index#26]
Links to collections on this page:
https://stacindex.org/catalogs/vito-openeo#/?t=0
Seem to be broken, tool generates wrong url's, e.g.: openeo/1.0/collections/collections/TERRASCOPE_S2_FCOVER_V2
```
{"code":"NotFound","id":"f7e642e9-274d-491b-b23d-a4f7d1eaecb6","message":"404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}

Please note that some servers don't allow external access via web browsers (e.g., when CORS headers are not present).

Errored URL: https://openeo.vito.be/openeo/1.0/collections/collections/TERRASCOPE_S2_FCOVER_V2
```

**Comment by m-mohr** [comment]
API support is limited in STAC Browser v2 (which is what we use here on STAC Index right now) and has some requirements for how the data must be given. I think what is missing in the VITO catalog are self links in the collections. parent and root links would also be very helpful, especially once we migrate to v3. See https://earthengine.openeo.org/v1.0/collections for an example.

The alpha version of v3 has already fixed it though, but it should work even better with the links mentioned above included: https://radiantearth.github.io/stac-browser/#/external/openeo.vito.be/openeo/1.0
STAC Index will migrate to v3 once it is a bit more stable.
