### ISSUE TITLE
Float number display issue

### ISSUE THREAD

**Issue by MarcYin** [stac-utils/stac-index#29]
Float number (0.0001) is displayed as 0

![Screenshot 2022-08-22 at 15 08 45](https://user-images.githubusercontent.com/19539641/185941701-5dcbce87-b32b-4677-b91e-f0320ba0f14d.png)

**Comment by m-mohr** [comment]
Thanks, which URL is this? I'd like to check whether it still occurs with STAC Browser v3, which we'll migrate to soon.

**Comment by MarcYin** [comment]
Hi, 

Here is the [URL](https://stacindex.org/catalogs/uk-nceo-analysis-ready-data-ard#/item/4safnd9oFZyD6hcoN1Kp2M4UuksYh3Crvph3Ropq/4safnd9oFZyD6hcoN1Kng4KqupDQdjjTMTqdJDUy/SLaPH6XagySDBbDqD3Vb8EQZ95stoH3EmzSRy8CTJGXnV/xh3GMSRcEhee7DRYVbHdnndGBRvZwmxrNff2zLK6sozJGAF7KJH3s/CADLVM48Wqqg5RfWG3Z968yaFnUMqp2zEb4maBBLoATDhAFDL6a2QV92gLtRyFQjXM5CRubG5GSVXDLEUVBSQGqtMDYaR?si=0#10/57.266421/-4.992595). I have turned off the CORS to view this STAC (UK NCEO ARD) by using a chrome extension or simply `Disable Cross-Origin Restrictions` in Safari Develop tab, otherwise it won't allow me to view it.

Thanks.

Marc.

**Comment by m-mohr** [comment]
Thanks, I've checked it with STAC Browser v3 and it works correctly:
https://radiantearth.github.io/stac-browser/#/external/gws-access.jasmin.ac.uk/public/nceo_ard/NCEO_ARD_STAC/UK-sentinel-2/30/30V/30VUJ/2017-01-08/S2A_30VUJ_20170108T113441.json

**Comment by MarcYin** [comment]
Yes, it works with the new version. Thanks a lot.
