### ISSUE TITLE
COG tiles displacement

### ISSUE THREAD

**Issue by MarcYin** [stac-utils/stac-index#30]
It seems the version 3 does not display COG file properly and tiles within the COG are slightly shifted. see the attached image:
![Screenshot 2022-08-23 at 11 41 42](https://user-images.githubusercontent.com/19539641/186139371-ddfe76c9-7758-44b8-a29d-a6e95969b54b.png).

This image is displayed fine with QGIS and online COG viewer [here](https://cholmes.github.io/cog-map/#/url/https%3A%2F%2Fgws-access.jasmin.ac.uk%2Fpublic%2Fnceo_ard%2FS2%2F30%2FV%2FUJ%2FS2A_MSIL1C_20170108T113441_N0204_R080_T30VUJ_20170108T113436.SAFE%2FGRANULE%2FL1C_T30VUJ_A008085_20170108T113436%2FIMG_DATA%2FTOA_RGB_cog.tif/center/-5.1381,57.2297/zoom/10.6)

**Comment by m-mohr** [comment]
That is a known issue of the geotiff plugin for leaflet used by STAC Browser: https://github.com/GeoTIFF/georaster-layer-for-leaflet/issues/77
Nothing I can do about it in STAC Browser or STAC Index, unfortunately.
