### ISSUE TITLE
Add learning resource: Working with Raster and Vector Data in Geospatial Python with STAC

### ISSUE THREAD

**Issue by rbavery** [stac-utils/stac-index#31]
Can we add this lesson to the learn section? https://carpentries-incubator.github.io/geospatial-python/
https://stacindex.org/learn
Or, how should I go about PRing this so it shows up as a learning resource?

Context: this is a Carpentries curriculum that takes a learner from "what's a raster?" to sourcing rasters from  STAC collections, handling projects, getting the data into xarray, and doing data analysis and plotting.

**Comment by m-mohr** [comment]
Just click (+) on the page and you'll end up in the submission form: https://stacindex.org/add :-)

**Comment by rbavery** [comment]
Done, thanks!
