### ISSUE TITLE
Refresh?

### ISSUE THREAD

**Issue by drwelby** [stac-utils/stac-index#32]
https://stacindex.org/catalogs/maxar-open-data-catalog-ard-format#/ seems stuck? Can you trigger a re-ingest?

Thanks Matthias!

**Comment by m-mohr** [comment]
I don't ingest any data, the data is loaded directly from the MAXAR catalog. Maybe it's a caching issue on your side?

Otherwise, what are you missing/is outdated?

**Comment by drwelby** [comment]
We recently updated to add the Turkey earthquake imagery. It doesn't appear to be a caching issue because a hard refresh doesn't update either. There are 17 catalogs and only 12 display, but I don't see any pagination and the order toggle doesn't do anything either. The same catalog in V3 shows: 

https://radiantearth.github.io/stac-browser/#/external/maxar-opendata.s3.amazonaws.com/events/catalog.json?.language=en

**Comment by m-mohr** [comment]
I see 17:

![grafik](https://user-images.githubusercontent.com/8262166/217857322-952692d0-375c-49c9-b8e8-29f78c1cbdd6.png)

**Comment by drwelby** [comment]
OK, looks like overzealous caching in my browser, thanks for the confirmation.
