### ISSUE TITLE
remove Radiant MLHub

### ISSUE THREAD

**Issue by guidorice** [stac-utils/stac-index#35]
Hi @m-mohr 👋🏽  Thanks for your efforts to maintain the stac index!
- Please remove https://stacindex.org/catalogs/radiant-mlhub
- As you know, MLHub was sunsetted, I guess it was a couple of years ago now. 😞 

Related discussion here about the next thing
https://github.com/radiantearth/source-cooperative/discussions/12

**Comment by m-mohr** [comment]
Hi @guidorice! Good point, thanks for catching it. I've remove the MLHub from STAC Index.
